license:
  existingSecret: ram-license

config:
  existingSecret: ram-config

service:
  type: ClusterIP

serviceAccount:
  create: true
  automount: false

server:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

worker:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

tests:
  enabled: false
